START TRANSACTION;

UPDATE foods SET name_id = 'Agar Rumput Laut' WHERE id = 9;
UPDATE foods SET name_id = 'Kacang almond' WHERE id = 3;
UPDATE foods SET name_id = 'Biji Adas Manis' WHERE id = 5;
UPDATE foods SET name_id = 'Kue Apel Renyah' WHERE id = 230;
UPDATE foods SET name_id = 'Apel' WHERE id = 6;
UPDATE foods SET name_id = 'Pir Asia' WHERE id = 8;
UPDATE foods SET name_id = 'Asparagus' WHERE id = 12;
UPDATE foods SET name_id = 'Alpukat' WHERE id = 14;
UPDATE foods SET name_id = 'Jagung Muda' WHERE id = 15;
UPDATE foods SET name_id = 'Makanan Bayi Daging Sapi' WHERE id = 304;
UPDATE foods SET name_id = 'Bayam muda' WHERE id = 17;
UPDATE foods SET name_id = 'Daging asap' WHERE id = 18;
UPDATE foods SET name_id = 'Baguette' WHERE id = 19;
UPDATE foods SET name_id = 'Ikan Panggang atau Bakar' WHERE id = 295;
UPDATE foods SET name_id = 'Dada Ayam Panggang atau Goreng dengan Kulit' WHERE id = 313;
UPDATE foods SET name_id = 'Sayap Ayam Goreng Tepung dengan Kulit' WHERE id = 779;
UPDATE foods SET name_id = 'Kentang Panggang (Kulitnya Dimakan)' WHERE id = 20;
UPDATE foods SET name_id = 'Baking Powder (Natrium Aluminium Sulfat, Kerja Ganda)' WHERE id = 21;
UPDATE foods SET name_id = 'Soda Kue' WHERE id = 22;
UPDATE foods SET name_id = 'Rebung' WHERE id = 24;
UPDATE foods SET name_id = 'Pisang' WHERE id = 26;
UPDATE foods SET name_id = 'Pisang' WHERE id = 25;
UPDATE foods SET name_id = 'Saus Barbekyu' WHERE id = 34;
UPDATE foods SET name_id = 'Kemangi' WHERE id = 30;
UPDATE foods SET name_id = 'Kemangi (Kering)' WHERE id = 257;
UPDATE foods SET name_id = 'Nasi Basmati' WHERE id = 31;
UPDATE foods SET name_id = 'Daun salam' WHERE id = 32;
UPDATE foods SET name_id = 'Tauge' WHERE id = 37;
UPDATE foods SET name_id = 'Daging sapi' WHERE id = 39;
UPDATE foods SET name_id = 'Daging Sapi (Hanya Daging Tanpa Lemak yang Dikonsumsi)' WHERE id = 448;
UPDATE foods SET name_id = 'Daging Sapi Panggang (Hash)' WHERE id = 44;
UPDATE foods SET name_id = 'Daging Sandung Lamur Sapi' WHERE id = 91;
UPDATE foods SET name_id = 'Daging Sandung Lamur Sapi (Utuh, Hanya Daging Tanpa Lemak)' WHERE id = 40;
UPDATE foods SET name_id = 'Hati Sapi' WHERE id = 46;
UPDATE foods SET name_id = 'Bakso Daging Sapi' WHERE id = 47;
UPDATE foods SET name_id = 'Saus Daging Sapi atau Daging Lainnya' WHERE id = 378;
UPDATE foods SET name_id = 'Ekor Sapi' WHERE id = 524;
UPDATE foods SET name_id = 'Rendang Daging Sapi' WHERE id = 604;
UPDATE foods SET name_id = 'Tulang Rusuk Sapi (Utuh, Dipangkas hingga menyisakan lemak 1/8 inci)' WHERE id = 48;
UPDATE foods SET name_id = 'Salami Daging Sapi' WHERE id = 49;
UPDATE foods SET name_id = 'Sosis Daging Sapi' WHERE id = 50;
UPDATE foods SET name_id = 'Potongan Daging Sapi Bagian Betis (Dipangkas hingga 1/4" Lemak, Kualitas Pilihan)' WHERE id = 51;
UPDATE foods SET name_id = 'Steak Daging Sapi' WHERE id = 52;
UPDATE foods SET name_id = 'Sup Daging Sapi dengan Kentang dan Sayuran dalam Kuah' WHERE id = 702;
UPDATE foods SET name_id = 'Tumis Daging Sapi' WHERE id = 53;
UPDATE foods SET name_id = 'Kaldu Sapi' WHERE id = 42;
UPDATE foods SET name_id = 'Daging Tenderloin Sapi (Dipangkas hingga menyisakan lemak 1/8 inci)' WHERE id = 54;
UPDATE foods SET name_id = 'Lidah Sapi (Dimasak, Direbus)' WHERE id = 55;
UPDATE foods SET name_id = 'Daging Sirloin Atas Sapi (Dipangkas hingga menyisakan lemak 1/8 inci)' WHERE id = 700;
UPDATE foods SET name_id = 'Babat Sapi (Dimasak, Direbus)' WHERE id = 748;
UPDATE foods SET name_id = 'Bit' WHERE id = 58;
UPDATE foods SET name_id = 'Paprika' WHERE id = 57;
UPDATE foods SET name_id = 'Buah beri' WHERE id = 59;
UPDATE foods SET name_id = 'Lada Hitam' WHERE id = 63;
UPDATE foods SET name_id = 'Teh Hitam' WHERE id = 64;
UPDATE foods SET name_id = 'Buah beri hitam' WHERE id = 65;
UPDATE foods SET name_id = 'Sosis Darah' WHERE id = 66;
UPDATE foods SET name_id = 'Buah blueberry' WHERE id = 67;
UPDATE foods SET name_id = 'Telur Rebus' WHERE id = 73;
UPDATE foods SET name_id = 'Kentang Rebus' WHERE id = 74;
UPDATE foods SET name_id = 'Roti' WHERE id = 86;
UPDATE foods SET name_id = 'Tepung roti' WHERE id = 87;
UPDATE foods SET name_id = 'Kue Pastry Sarapan' WHERE id = 538;
UPDATE foods SET name_id = 'Brokoli' WHERE id = 92;
UPDATE foods SET name_id = 'Brokoli (dengan Garam, Tiriskan, Masak, Rebus)' WHERE id = 69;
UPDATE foods SET name_id = 'Beras merah' WHERE id = 94;
UPDATE foods SET name_id = 'Gula merah' WHERE id = 95;
UPDATE foods SET name_id = 'Mentega' WHERE id = 102;
UPDATE foods SET name_id = 'Mentega (Asin)' WHERE id = 640;
UPDATE foods SET name_id = 'Kubis' WHERE id = 104;
UPDATE foods SET name_id = 'Ikan teri kalengan' WHERE id = 4;
UPDATE foods SET name_id = 'Minyak Sayur Kanola' WHERE id = 110;
UPDATE foods SET name_id = 'Melon Cantaloupe' WHERE id = 111;
UPDATE foods SET name_id = 'Carambola (Buah Bintang)' WHERE id = 699;
UPDATE foods SET name_id = 'Air Berkarbonasi Tanpa Pemanis' WHERE id = 679;
UPDATE foods SET name_id = 'Kapulaga' WHERE id = 113;
UPDATE foods SET name_id = 'Ikan Mas' WHERE id = 114;
UPDATE foods SET name_id = 'Wortel' WHERE id = 115;
UPDATE foods SET name_id = 'Wortel (Tanpa Garam, Ditiriskan, Dimasak, Direbus)' WHERE id = 70;
UPDATE foods SET name_id = 'Kacang mente' WHERE id = 116;
UPDATE foods SET name_id = 'Kentang Goreng Singkong' WHERE id = 71;
UPDATE foods SET name_id = 'Kembang kol' WHERE id = 119;
UPDATE foods SET name_id = 'Seledri' WHERE id = 122;
UPDATE foods SET name_id = 'Seledri' WHERE id = 123;
UPDATE foods SET name_id = 'Labu siam (Buah, dengan Garam, Ditiriskan, Direbus, Dimasak)' WHERE id = 126;
UPDATE foods SET name_id = 'Keju Cheddar' WHERE id = 125;
UPDATE foods SET name_id = 'Biskuit Keju' WHERE id = 127;
UPDATE foods SET name_id = 'Saus Keju' WHERE id = 129;
UPDATE foods SET name_id = 'Olesan Keju' WHERE id = 128;
UPDATE foods SET name_id = 'Burger Keju (Satu Patty dengan Bumbu Pelengkap)' WHERE id = 100;
UPDATE foods SET name_id = 'Ayam' WHERE id = 164;
UPDATE foods SET name_id = 'Dada ayam' WHERE id = 133;
UPDATE foods SET name_id = 'Sup Jagung Ayam dengan Mie (Resep Rumahan)' WHERE id = 212;
UPDATE foods SET name_id = 'Kari Ayam' WHERE id = 138;
UPDATE foods SET name_id = 'Paha Ayam' WHERE id = 263;
UPDATE foods SET name_id = 'Telur Ayam Foo Yung' WHERE id = 140;
UPDATE foods SET name_id = 'Lemak Ayam' WHERE id = 143;
UPDATE foods SET name_id = 'Ceker ayam' WHERE id = 142;
UPDATE foods SET name_id = 'Nasi Goreng Ayam' WHERE id = 402;
UPDATE foods SET name_id = 'Ampela Ayam' WHERE id = 358;
UPDATE foods SET name_id = 'Ampela Ayam (Direbus, Dimasak)' WHERE id = 144;
UPDATE foods SET name_id = 'Jantung Ayam' WHERE id = 147;
UPDATE foods SET name_id = 'Hati Ayam (Digoreng, Dimasak)' WHERE id = 148;
UPDATE foods SET name_id = 'Hati Ayam Cincang dengan Telur dan Bawang Bombay (Campuran)' WHERE id = 141;
UPDATE foods SET name_id = 'Daging Ayam (Panggang)' WHERE id = 149;
UPDATE foods SET name_id = 'Bakso Ayam' WHERE id = 151;
UPDATE foods SET name_id = 'Sup Mie Ayam (Resep Rumahan)' WHERE id = 150;
UPDATE foods SET name_id = 'Nugget Ayam' WHERE id = 153;
UPDATE foods SET name_id = 'Ayam atau Kalkun A La King dengan Sayuran dalam Saus Krim, Putih, atau Berbasis Sup' WHERE id = 139;
UPDATE foods SET name_id = 'Ayam atau Kalkun dan Mie (Campuran)' WHERE id = 152;
UPDATE foods SET name_id = 'Sosis Ayam' WHERE id = 154;
UPDATE foods SET name_id = 'Kulit Ayam' WHERE id = 157;
UPDATE foods SET name_id = 'Sup ayam' WHERE id = 158;
UPDATE foods SET name_id = 'Tumis Ayam' WHERE id = 338;
UPDATE foods SET name_id = 'Kaldu Ayam' WHERE id = 93;
UPDATE foods SET name_id = 'Paha Ayam' WHERE id = 159;
UPDATE foods SET name_id = 'Paha Ayam (Kulit Tidak Dimakan)' WHERE id = 162;
UPDATE foods SET name_id = 'Sayap Ayam' WHERE id = 781;
UPDATE foods SET name_id = 'Sayap Ayam (Kulitnya Dimakan)' WHERE id = 163;
UPDATE foods SET name_id = 'Sup Ayam dengan Pasta Berbentuk Bintang (Kental, Kalengan)' WHERE id = 697;
UPDATE foods SET name_id = 'Cabai' WHERE id = 166;
UPDATE foods SET name_id = 'Minyak Cabai' WHERE id = 168;
UPDATE foods SET name_id = 'Bubuk Cabai' WHERE id = 172;
UPDATE foods SET name_id = 'Sawi putih' WHERE id = 175;
UPDATE foods SET name_id = 'Kubis Cina (Bok-Choy, Pak-Choi)' WHERE id = 77;
UPDATE foods SET name_id = 'Daun bawang' WHERE id = 177;
UPDATE foods SET name_id = 'Kue Cokelat Chip' WHERE id = 179;
UPDATE foods SET name_id = 'Mie Chow Mein' WHERE id = 320;
UPDATE foods SET name_id = 'Ketumbar' WHERE id = 182;
UPDATE foods SET name_id = 'Ketumbar (Coriander)' WHERE id = 207;
UPDATE foods SET name_id = 'Kayu manis' WHERE id = 183;
UPDATE foods SET name_id = 'Kerang' WHERE id = 185;
UPDATE foods SET name_id = 'Cengkeh (Bubuk)' WHERE id = 187;
UPDATE foods SET name_id = 'Koktail' WHERE id = 189;
UPDATE foods SET name_id = 'Bubuk Kakao (Tanpa Pemanis)' WHERE id = 192;
UPDATE foods SET name_id = 'Kelapa' WHERE id = 199;
UPDATE foods SET name_id = 'Daging Kelapa' WHERE id = 195;
UPDATE foods SET name_id = 'Air Kelapa' WHERE id = 197;
UPDATE foods SET name_id = 'Kopi' WHERE id = 200;
UPDATE foods SET name_id = 'Salad kol' WHERE id = 202;
UPDATE foods SET name_id = 'Pare yang Dimasak' WHERE id = 62;
UPDATE foods SET name_id = 'Singkong yang dimasak (Yuca Blanca)' WHERE id = 118;
UPDATE foods SET name_id = 'Jagung Matang (dari Jagung Segar, Lemak Tidak Ditambahkan Saat Memasak)' WHERE id = 268;
UPDATE foods SET name_id = 'Kacang panjang, kacang polong, atau kacang hitam yang sudah dimasak (dari yang segar)' WHERE id = 217;
UPDATE foods SET name_id = 'Terong yang Dimasak (Lemak Ditambahkan Saat Memasak)' WHERE id = 280;
UPDATE foods SET name_id = 'Ikan yang dimasak' WHERE id = 299;
UPDATE foods SET name_id = 'Cabai Pedas yang Dimasak' WHERE id = 170;
UPDATE foods SET name_id = 'Ikan Makarel yang Dimasak' WHERE id = 467;
UPDATE foods SET name_id = 'Jamur yang Dimasak' WHERE id = 784;
UPDATE foods SET name_id = 'Kerang yang dimasak' WHERE id = 493;
UPDATE foods SET name_id = 'Kacang Pinto, Calico, atau Kacang Merah yang Sudah Dimasak (Lemak Tidak Ditambahkan Saat Memasak)' WHERE id = 36;
UPDATE foods SET name_id = 'Labu yang dimasak' WHERE id = 580;
UPDATE foods SET name_id = 'Nasi' WHERE id = 204;
UPDATE foods SET name_id = 'Kedelai yang Dimasak (Lemak Tidak Ditambahkan Saat Memasak)' WHERE id = 684;
UPDATE foods SET name_id = 'Tuna yang dimasak' WHERE id = 206;
UPDATE foods SET name_id = 'Sayuran yang Dimasak (dari Sayuran Segar, Lemak Tidak Ditambahkan Saat Memasak)' WHERE id = 759;
UPDATE foods SET name_id = 'Jagung Kuning yang Dimasak' WHERE id = 388;
UPDATE foods SET name_id = 'Biji Ketumbar' WHERE id = 208;
UPDATE foods SET name_id = 'Jagung' WHERE id = 209;
UPDATE foods SET name_id = 'Minyak Jagung' WHERE id = 213;
UPDATE foods SET name_id = 'Daging Sandung Lamur Asin (Diawetkan)' WHERE id = 215;
UPDATE foods SET name_id = 'Kepiting' WHERE id = 218;
UPDATE foods SET name_id = 'Kerupuk' WHERE id = 223;
UPDATE foods SET name_id = 'Krim keju' WHERE id = 226;
UPDATE foods SET name_id = 'Sup Krim' WHERE id = 228;
UPDATE foods SET name_id = 'Timun' WHERE id = 180;
UPDATE foods SET name_id = 'Mentimun (dengan Kulit)' WHERE id = 235;
UPDATE foods SET name_id = 'Acar Timun' WHERE id = 554;
UPDATE foods SET name_id = 'Salad Timun dengan Cuka' WHERE id = 236;
UPDATE foods SET name_id = 'Jinten' WHERE id = 237;
UPDATE foods SET name_id = 'Cupcake dengan Icing' WHERE id = 238;
UPDATE foods SET name_id = 'Bubuk Kari' WHERE id = 242;
UPDATE foods SET name_id = 'Puding' WHERE id = 243;
UPDATE foods SET name_id = 'Tanggal' WHERE id = 247;
UPDATE foods SET name_id = 'Kentang Goreng Tepung (dari Fresh)' WHERE id = 325;
UPDATE foods SET name_id = 'Roti Gulung untuk Makan Malam' WHERE id = 623;
UPDATE foods SET name_id = 'Donat' WHERE id = 254;
UPDATE foods SET name_id = 'Sarden Kering' WHERE id = 256;
UPDATE foods SET name_id = 'Udang Kering' WHERE id = 262;
UPDATE foods SET name_id = 'Mie Beras Kering' WHERE id = 264;
UPDATE foods SET name_id = 'Telur Bebek' WHERE id = 266;
UPDATE foods SET name_id = 'Daging Bebek' WHERE id = 265;
UPDATE foods SET name_id = 'Keju Edam' WHERE id = 269;
UPDATE foods SET name_id = 'Belut' WHERE id = 270;
UPDATE foods SET name_id = 'Telur' WHERE id = 271;
UPDATE foods SET name_id = 'Telur (Utuh)' WHERE id = 780;
UPDATE foods SET name_id = 'Mie Telur (Diperkaya, Dimasak)' WHERE id = 272;
UPDATE foods SET name_id = 'Omelet Telur atau Telur Orak-arik' WHERE id = 273;
UPDATE foods SET name_id = 'Omelet Telur atau Telur Orak-arik dengan Sayuran' WHERE id = 513;
UPDATE foods SET name_id = 'Lumpia Isi Daging Sapi dan/atau Babi' WHERE id = 274;
UPDATE foods SET name_id = 'Putih Telur' WHERE id = 276;
UPDATE foods SET name_id = 'Kuning Telur' WHERE id = 277;
UPDATE foods SET name_id = 'Kuning Telur (Asin, Beku)' WHERE id = 641;
UPDATE foods SET name_id = 'Terung' WHERE id = 278;
UPDATE foods SET name_id = 'Jamur Enoki' WHERE id = 283;
UPDATE foods SET name_id = 'Minyak Zaitun Extra Virgin' WHERE id = 286;
UPDATE foods SET name_id = 'Umbi Adas' WHERE id = 288;
UPDATE foods SET name_id = 'Biji Fenugreek' WHERE id = 289;
UPDATE foods SET name_id = 'Fettuccine' WHERE id = 291;
UPDATE foods SET name_id = 'Filet Mignon' WHERE id = 292;
UPDATE foods SET name_id = 'Saus Ikan' WHERE id = 302;
UPDATE foods SET name_id = 'Kaldu Ikan (Resep Rumahan)' WHERE id = 303;
UPDATE foods SET name_id = 'Roti Prancis atau Roti Wina (Termasuk Roti Sourdough)' WHERE id = 306;
UPDATE foods SET name_id = 'Daging Ham Segar' WHERE id = 310;
UPDATE foods SET name_id = 'Sosis Babi Segar' WHERE id = 646;
UPDATE foods SET name_id = 'Terong Goreng Tepung' WHERE id = 319;
UPDATE foods SET name_id = 'Ikan Lele Goreng Tepung' WHERE id = 120;
UPDATE foods SET name_id = 'Ikan Goreng Tepung' WHERE id = 318;
UPDATE foods SET name_id = 'Cumi Goreng Tepung Roti' WHERE id = 330;
UPDATE foods SET name_id = 'Telur goreng' WHERE id = 317;
UPDATE foods SET name_id = 'Ham Goreng' WHERE id = 312;
UPDATE foods SET name_id = 'Udang Goreng Tepung atau Berlapis Tepung Roti' WHERE id = 329;
UPDATE foods SET name_id = 'Kentang Goreng' WHERE id = 326;
UPDATE foods SET name_id = 'Nasi Goreng' WHERE id = 327;
UPDATE foods SET name_id = 'Tahu goreng' WHERE id = 331;
UPDATE foods SET name_id = 'Bluberi Beku' WHERE id = 334;
UPDATE foods SET name_id = 'Buah' WHERE id = 337;
UPDATE foods SET name_id = 'Es buah' WHERE id = 658;
UPDATE foods SET name_id = 'Minuman Buah (dibuat dengan jus buah dan soda)' WHERE id = 582;
UPDATE foods SET name_id = 'Bawang putih' WHERE id = 345;
UPDATE foods SET name_id = 'Bubuk Bawang Putih' WHERE id = 347;
UPDATE foods SET name_id = 'Bubuk Gelatin (Tanpa Pemanis)' WHERE id = 351;
UPDATE foods SET name_id = 'Camilan Gelatin' WHERE id = 573;
UPDATE foods SET name_id = 'Jahe' WHERE id = 355;
UPDATE foods SET name_id = 'Jahe (Bubuk)' WHERE id = 394;
UPDATE foods SET name_id = 'Nasi Putih Ketan' WHERE id = 361;
UPDATE foods SET name_id = 'Kepala Kambing' WHERE id = 405;
UPDATE foods SET name_id = 'Daging Kambing' WHERE id = 362;
UPDATE foods SET name_id = 'Daging Kambing (Dimasak, Dipanggang)' WHERE id = 363;
UPDATE foods SET name_id = 'Tulang Rusuk Kambing' WHERE id = 364;
UPDATE foods SET name_id = 'Daging Angsa (Matang, Panggang)' WHERE id = 368;
UPDATE foods SET name_id = 'Apel Granny Smith' WHERE id = 369;
UPDATE foods SET name_id = 'Gula pasir' WHERE id = 370;
UPDATE foods SET name_id = 'Jeruk bali' WHERE id = 371;
UPDATE foods SET name_id = 'Anggur (Merah atau Hijau, Varietas Tipe Eropa Seperti Thompson Seedless)' WHERE id = 372;
UPDATE foods SET name_id = 'Keju Cheddar Kering Parut atau Keju Jenis Amerika' WHERE id = 375;
UPDATE foods SET name_id = 'Keju Romano Parut' WHERE id = 374;
UPDATE foods SET name_id = 'Cabai Hijau (Kalengan)' WHERE id = 382;
UPDATE foods SET name_id = 'Kacang Polong Hijau' WHERE id = 539;
UPDATE foods SET name_id = 'Paprika Hijau' WHERE id = 385;
UPDATE foods SET name_id = 'Kacang Panjang Hijau' WHERE id = 379;
UPDATE foods SET name_id = 'Teh hijau' WHERE id = 386;
UPDATE foods SET name_id = 'Tomat Hijau' WHERE id = 387;
UPDATE foods SET name_id = 'Ayam Panggang' WHERE id = 146;
UPDATE foods SET name_id = 'Daging Sapi Giling (Matang)' WHERE id = 389;
UPDATE foods SET name_id = 'Daging Rusa Giling' WHERE id = 248;
UPDATE foods SET name_id = 'Daging Giling' WHERE id = 481;
UPDATE foods SET name_id = 'Ikan kerapu (Spesies Campuran)' WHERE id = 397;
UPDATE foods SET name_id = 'Jambu biji' WHERE id = 398;
UPDATE foods SET name_id = 'Roti Hamburger atau Hotdog' WHERE id = 99;
UPDATE foods SET name_id = 'Hash' WHERE id = 404;
UPDATE foods SET name_id = 'Krim Kental' WHERE id = 225;
UPDATE foods SET name_id = 'Saus Hoisin' WHERE id = 407;
UPDATE foods SET name_id = 'Saus Spaghetti Ala Rumahan dengan Daging Sapi atau Daging Lainnya' WHERE id = 80;
UPDATE foods SET name_id = 'Sayang' WHERE id = 408;
UPDATE foods SET name_id = 'Cabai Pedas' WHERE id = 169;
UPDATE foods SET name_id = 'Selada Iceberg (Termasuk Jenis Crisphead)' WHERE id = 416;
UPDATE foods SET name_id = 'Imitasi Kepiting Raja Alaska (Terbuat dari Surimi)' WHERE id = 709;
UPDATE foods SET name_id = 'Saus Salad Italia' WHERE id = 631;
UPDATE foods SET name_id = 'Nangka' WHERE id = 420;
UPDATE foods SET name_id = 'Selai Manisan' WHERE id = 421;
UPDATE foods SET name_id = 'Jeli (Semua Rasa)' WHERE id = 424;
UPDATE foods SET name_id = 'Bikuma' WHERE id = 425;
UPDATE foods SET name_id = 'Kubis' WHERE id = 433;
UPDATE foods SET name_id = 'Kebab' WHERE id = 434;
UPDATE foods SET name_id = 'Rumput Laut Kelp' WHERE id = 436;
UPDATE foods SET name_id = 'Buah Kiwi' WHERE id = 440;
UPDATE foods SET name_id = 'Domba' WHERE id = 444;
UPDATE foods SET name_id = 'Iga Domba' WHERE id = 445;
UPDATE foods SET name_id = 'Lasagna dengan Daging' WHERE id = 447;
UPDATE foods SET name_id = 'Bawang perai' WHERE id = 450;
UPDATE foods SET name_id = 'Daun bawang' WHERE id = 451;
UPDATE foods SET name_id = 'Jeruk nipis' WHERE id = 452;
UPDATE foods SET name_id = 'Air jeruk' WHERE id = 453;
UPDATE foods SET name_id = 'Kulit Lemon' WHERE id = 454;
UPDATE foods SET name_id = 'Selada' WHERE id = 415;
UPDATE foods SET name_id = 'Salad Selada dengan Aneka Sayuran' WHERE id = 757;
UPDATE foods SET name_id = 'Kapur' WHERE id = 431;
UPDATE foods SET name_id = 'Jus Jeruk Nipis' WHERE id = 427;
UPDATE foods SET name_id = 'Jeruk nipis' WHERE id = 458;
UPDATE foods SET name_id = 'Lobster' WHERE id = 460;
UPDATE foods SET name_id = 'Lontong Sayur' WHERE id = 462;
UPDATE foods SET name_id = 'Susu Rendah Lemak' WHERE id = 463;
UPDATE foods SET name_id = 'Daging Kaleng' WHERE id = 464;
UPDATE foods SET name_id = 'Leci' WHERE id = 465;
UPDATE foods SET name_id = 'Makaroni' WHERE id = 466;
UPDATE foods SET name_id = 'Mahi Mahi' WHERE id = 468;
UPDATE foods SET name_id = 'Mangga' WHERE id = 470;
UPDATE foods SET name_id = 'Margarin' WHERE id = 472;
UPDATE foods SET name_id = 'Bawang Merah Matang' WHERE id = 771;
UPDATE foods SET name_id = 'Perkedel Matzo' WHERE id = 756;
UPDATE foods SET name_id = 'Mayones' WHERE id = 473;
UPDATE foods SET name_id = 'Daging' WHERE id = 474;
UPDATE foods SET name_id = 'Sup Bakso Khas Meksiko (Sopa De Albondigas)' WHERE id = 475;
UPDATE foods SET name_id = 'Susu (Susu Murni)' WHERE id = 340;
UPDATE foods SET name_id = 'Susu kocok' WHERE id = 478;
UPDATE foods SET name_id = 'Ikan bandeng (Dimasak, dengan api kering)' WHERE id = 480;
UPDATE foods SET name_id = 'Bawang Putih Cincang' WHERE id = 190;
UPDATE foods SET name_id = 'Sayuran Salad Campur' WHERE id = 630;
UPDATE foods SET name_id = 'Keju Mozzarella' WHERE id = 488;
UPDATE foods SET name_id = 'Keju Mozzarella (Susu Murni)' WHERE id = 490;
UPDATE foods SET name_id = 'Jamur' WHERE id = 492;
UPDATE foods SET name_id = 'Moster' WHERE id = 494;
UPDATE foods SET name_id = 'Sawi Hijau' WHERE id = 495;
UPDATE foods SET name_id = 'Saus Mustard' WHERE id = 496;
UPDATE foods SET name_id = 'Nasi Putih' WHERE id = 498;
UPDATE foods SET name_id = 'Jeruk Navel' WHERE id = 500;
UPDATE foods SET name_id = 'Mie' WHERE id = 501;
UPDATE foods SET name_id = 'Pala (Bubuk)' WHERE id = 395;
UPDATE foods SET name_id = 'Havermut' WHERE id = 506;
UPDATE foods SET name_id = 'Gurita' WHERE id = 508;
UPDATE foods SET name_id = 'Jagung Popcorn Putih yang Dipanggang dengan Minyak' WHERE id = 563;
UPDATE foods SET name_id = 'Minyak zaitun' WHERE id = 512;
UPDATE foods SET name_id = 'Bubuk Bawang' WHERE id = 518;
UPDATE foods SET name_id = 'Bawang' WHERE id = 517;
UPDATE foods SET name_id = 'Jus jeruk' WHERE id = 426;
UPDATE foods SET name_id = 'Jeruk' WHERE id = 519;
UPDATE foods SET name_id = 'Oregano' WHERE id = 258;
UPDATE foods SET name_id = 'Aneka Camilan Oriental (Kerupuk Nasi Cabai, Kacang Polong Goreng, Stik Wijen, dan Kacang Tanah)' WHERE id = 322;
UPDATE foods SET name_id = 'Jamur Tiram' WHERE id = 526;
UPDATE foods SET name_id = 'Tiram' WHERE id = 525;
UPDATE foods SET name_id = 'Pepaya' WHERE id = 531;
UPDATE foods SET name_id = 'Paprika' WHERE id = 532;
UPDATE foods SET name_id = 'Keju Parmesan (Parut)' WHERE id = 376;
UPDATE foods SET name_id = 'Keju Parmesan (Parut)' WHERE id = 534;
UPDATE foods SET name_id = 'Peterseli' WHERE id = 181;
UPDATE foods SET name_id = 'Peterseli (Kering)' WHERE id = 259;
UPDATE foods SET name_id = 'Pasta dengan Saus Carbonara' WHERE id = 112;
UPDATE foods SET name_id = 'Persik' WHERE id = 540;
UPDATE foods SET name_id = 'Selai kacang' WHERE id = 541;
UPDATE foods SET name_id = 'Bumbu kacang' WHERE id = 542;
UPDATE foods SET name_id = 'Kacang tanah' WHERE id = 543;
UPDATE foods SET name_id = 'Buah pir' WHERE id = 544;
UPDATE foods SET name_id = 'Penne' WHERE id = 535;
UPDATE foods SET name_id = 'Steak Lada Hitam' WHERE id = 638;
UPDATE foods SET name_id = 'Peppermint (Mint)' WHERE id = 482;
UPDATE foods SET name_id = 'Acar' WHERE id = 555;
UPDATE foods SET name_id = 'Pai' WHERE id = 557;
UPDATE foods SET name_id = 'Nanas' WHERE id = 556;
UPDATE foods SET name_id = 'Biskuit Biasa atau Biskuit Buttermilk' WHERE id = 61;
UPDATE foods SET name_id = 'Pancake Biasa' WHERE id = 529;
UPDATE foods SET name_id = 'Yogurt Tawar' WHERE id = 558;
UPDATE foods SET name_id = 'Yogurt Tawar (Susu Murni)' WHERE id = 789;
UPDATE foods SET name_id = 'Telur Rebus' WHERE id = 559;
UPDATE foods SET name_id = 'Delima' WHERE id = 562;
UPDATE foods SET name_id = 'Kari Babi' WHERE id = 240;
UPDATE foods SET name_id = 'Pangsit Goreng Babi' WHERE id = 315;
UPDATE foods SET name_id = 'Daging Pinggang Babi (Tenderloin)' WHERE id = 564;
UPDATE foods SET name_id = 'Sosis Babi (Matang)' WHERE id = 647;
UPDATE foods SET name_id = 'Keripik kentang' WHERE id = 176;
UPDATE foods SET name_id = 'Kroket Kentang' WHERE id = 570;
UPDATE foods SET name_id = 'Kentang Goreng' WHERE id = 307;
UPDATE foods SET name_id = 'Kentang (Daging, dengan Garam, Direbus)' WHERE id = 75;
UPDATE foods SET name_id = 'Gula Bubuk' WHERE id = 574;
UPDATE foods SET name_id = 'Udang' WHERE id = 576;
UPDATE foods SET name_id = 'Kue Puff' WHERE id = 579;
UPDATE foods SET name_id = 'Telur Puyuh' WHERE id = 585;
UPDATE foods SET name_id = 'Lobak' WHERE id = 590;
UPDATE foods SET name_id = 'Pasta Kari Merah' WHERE id = 241;
UPDATE foods SET name_id = 'Apel Red Delicious' WHERE id = 593;
UPDATE foods SET name_id = 'Red Hot Chili Peppers' WHERE id = 597;
UPDATE foods SET name_id = 'Kacang Merah (dengan Garam, Dimasak, Direbus)' WHERE id = 594;
UPDATE foods SET name_id = 'Bawang Merah' WHERE id = 599;
UPDATE foods SET name_id = 'Paprika Merah Manis' WHERE id = 546;
UPDATE foods SET name_id = 'Anggur Meja Merah' WHERE id = 603;
UPDATE foods SET name_id = 'Tomat Merah' WHERE id = 602;
UPDATE foods SET name_id = 'Tomat Merah (dengan Cabai Hijau, Kalengan)' WHERE id = 598;
UPDATE foods SET name_id = 'Kecap Asin Rendah Garam' WHERE id = 456;
UPDATE foods SET name_id = 'Campuran Oriental Berbasis Nasi' WHERE id = 609;
UPDATE foods SET name_id = 'Mie Beras (Matang)' WHERE id = 610;
UPDATE foods SET name_id = 'Kertas Nasi' WHERE id = 611;
UPDATE foods SET name_id = 'Anggur Beras' WHERE id = 618;
UPDATE foods SET name_id = 'Rigatoni' WHERE id = 620;
UPDATE foods SET name_id = 'Kentang Panggang' WHERE id = 567;
UPDATE foods SET name_id = 'Kacang Mete Panggang Asin' WHERE id = 117;
UPDATE foods SET name_id = 'Rosemary' WHERE id = 627;
UPDATE foods SET name_id = 'Roti' WHERE id = 629;
UPDATE foods SET name_id = 'Daging Panggang Bagian Pantat' WHERE id = 621;
UPDATE foods SET name_id = 'Ikan salmon' WHERE id = 632;
UPDATE foods SET name_id = 'Garam' WHERE id = 636;
UPDATE foods SET name_id = 'Makarel Asin' WHERE id = 639;
UPDATE foods SET name_id = 'Sarden dalam Minyak (Kalengan)' WHERE id = 643;
UPDATE foods SET name_id = 'Gurih (Bubuk)' WHERE id = 649;
UPDATE foods SET name_id = 'Daun bawang atau bawang bombay' WHERE id = 650;
UPDATE foods SET name_id = 'Telur Orak-arik' WHERE id = 281;
UPDATE foods SET name_id = 'Telur Orak-arik (Utuh, Matang)' WHERE id = 275;
UPDATE foods SET name_id = 'Minyak Wijen' WHERE id = 655;
UPDATE foods SET name_id = 'Bawang merah' WHERE id = 657;
UPDATE foods SET name_id = 'Jamur Shiitake (Tanpa Garam, Dimasak)' WHERE id = 661;
UPDATE foods SET name_id = 'Mie Shirataki' WHERE id = 662;
UPDATE foods SET name_id = 'Ayam Suwir' WHERE id = 665;
UPDATE foods SET name_id = 'Udang' WHERE id = 309;
UPDATE foods SET name_id = 'Pasta Udang' WHERE id = 667;
UPDATE foods SET name_id = 'Dada Ayam Tanpa Kulit' WHERE id = 72;
UPDATE foods SET name_id = 'Ikan Asap' WHERE id = 675;
UPDATE foods SET name_id = 'Ikan Kakap (Spesies Campuran)' WHERE id = 676;
UPDATE foods SET name_id = 'Kacang Polong Salju atau Kacang Polong Manis' WHERE id = 677;
UPDATE foods SET name_id = 'Soda' WHERE id = 678;
UPDATE foods SET name_id = 'Ikan Sole' WHERE id = 681;
UPDATE foods SET name_id = 'Sup' WHERE id = 682;
UPDATE foods SET name_id = 'Susu Kedelai' WHERE id = 683;
UPDATE foods SET name_id = 'Spageti' WHERE id = 685;
UPDATE foods SET name_id = 'Spageti Bolognese' WHERE id = 79;
UPDATE foods SET name_id = 'Bayam' WHERE id = 691;
UPDATE foods SET name_id = 'Cumi-cumi' WHERE id = 244;
UPDATE foods SET name_id = 'Pangsit Kukus (Isi Daging, Unggas, atau Makanan Laut)' WHERE id = 267;
UPDATE foods SET name_id = 'Kepiting Cangkang Keras Kukus' WHERE id = 221;
UPDATE foods SET name_id = 'Udang Kukus atau Rebus' WHERE id = 76;
UPDATE foods SET name_id = 'Cumi Kukus atau Rebus' WHERE id = 696;
UPDATE foods SET name_id = 'Nasi Kukus' WHERE id = 701;
UPDATE foods SET name_id = 'Ketan' WHERE id = 422;
UPDATE foods SET name_id = 'Tumis Sayuran' WHERE id = 703;
UPDATE foods SET name_id = 'Stroberi' WHERE id = 705;
UPDATE foods SET name_id = 'Gula' WHERE id = 528;
UPDATE foods SET name_id = 'Donat Bertabur Gula atau Glasir' WHERE id = 251;
UPDATE foods SET name_id = 'Donat Bertabur Gula atau Glasir' WHERE id = 252;
UPDATE foods SET name_id = 'Sushi' WHERE id = 710;
UPDATE foods SET name_id = 'Sushi Onigiri' WHERE id = 516;
UPDATE foods SET name_id = 'Saus Asam Manis' WHERE id = 711;
UPDATE foods SET name_id = 'Ubi jalar' WHERE id = 715;
UPDATE foods SET name_id = 'Paprika Merah Manis' WHERE id = 552;
UPDATE foods SET name_id = 'Daun ubi jalar, daun labu, daun waluh, daun krisan, daun buncis, atau kubis rawa (lemak tidak ditambahkan saat memasak)' WHERE id = 23;
UPDATE foods SET name_id = 'Sirup' WHERE id = 718;
UPDATE foods SET name_id = 'Taco atau Tostada dengan Daging Sapi, Keju, dan Selada' WHERE id = 719;
UPDATE foods SET name_id = 'Asam jawa' WHERE id = 720;
UPDATE foods SET name_id = 'Jeruk keprok' WHERE id = 722;
UPDATE foods SET name_id = 'Talas' WHERE id = 726;
UPDATE foods SET name_id = 'Teh (Seduh)' WHERE id = 727;
UPDATE foods SET name_id = 'Tempe (Matang)' WHERE id = 729;
UPDATE foods SET name_id = 'Timi' WHERE id = 736;
UPDATE foods SET name_id = 'Roti Putih Panggang' WHERE id = 738;
UPDATE foods SET name_id = 'Sup Tom Yum' WHERE id = 741;
UPDATE foods SET name_id = 'Saus Tomat Cabai' WHERE id = 743;
UPDATE foods SET name_id = 'Jus tomat' WHERE id = 744;
UPDATE foods SET name_id = 'Puree Tomat' WHERE id = 746;
UPDATE foods SET name_id = 'Saus Tomat' WHERE id = 645;
UPDATE foods SET name_id = 'Tomat' WHERE id = 742;
UPDATE foods SET name_id = 'Pakis Pohon (dengan Garam, Dimasak)' WHERE id = 290;
UPDATE foods SET name_id = 'Tuna' WHERE id = 311;
UPDATE foods SET name_id = 'Tuna dalam Air (Kalengan)' WHERE id = 107;
UPDATE foods SET name_id = 'Kunyit (Bubuk)' WHERE id = 396;
UPDATE foods SET name_id = 'Ekstrak Vanili' WHERE id = 753;
UPDATE foods SET name_id = 'Es Krim Vanila' WHERE id = 754;
UPDATE foods SET name_id = 'Minyak Sayur' WHERE id = 510;
UPDATE foods SET name_id = 'Sup Sayur (Resep Rumahan)' WHERE id = 758;
UPDATE foods SET name_id = 'Lumpia Sayuran' WHERE id = 692;
UPDATE foods SET name_id = 'Tempura Sayuran' WHERE id = 731;
UPDATE foods SET name_id = 'Bihun' WHERE id = 760;
UPDATE foods SET name_id = 'Cuka' WHERE id = 761;
UPDATE foods SET name_id = 'Air' WHERE id = 411;
UPDATE foods SET name_id = 'Kangkung' WHERE id = 762;
UPDATE foods SET name_id = 'Selada air' WHERE id = 763;
UPDATE foods SET name_id = 'Semangka' WHERE id = 764;
UPDATE foods SET name_id = 'Perkedel Tepung Terigu' WHERE id = 333;
UPDATE foods SET name_id = 'Krim Kocok' WHERE id = 768;
UPDATE foods SET name_id = 'Lada Putih' WHERE id = 773;
UPDATE foods SET name_id = 'Nasi putih' WHERE id = 606;
UPDATE foods SET name_id = 'Tepung Beras Putih' WHERE id = 608;
UPDATE foods SET name_id = 'Saus Putih (Sedang)' WHERE id = 774;
UPDATE foods SET name_id = 'Anggur Meja Putih' WHERE id = 776;
UPDATE foods SET name_id = 'Tepung Terigu Putih (Diperkaya)' WHERE id = 770;
UPDATE foods SET name_id = 'Kapur sirih' WHERE id = 777;
UPDATE foods SET name_id = 'Susu Bubuk Utuh' WHERE id = 572;
UPDATE foods SET name_id = 'Susu Murni' WHERE id = 477;
UPDATE foods SET name_id = 'Roti Gandum Utuh' WHERE id = 765;
UPDATE foods SET name_id = 'Pangsit (Pangsit Goreng Isi Daging)' WHERE id = 782;
UPDATE foods SET name_id = 'Ragi' WHERE id = 787;
UPDATE foods SET name_id = 'Kue Kuning (dengan Krim Vanila)' WHERE id = 105;
UPDATE foods SET name_id = 'Biji Mustar Kuning' WHERE id = 497;
UPDATE foods SET name_id = 'Jagung Manis Kuning' WHERE id = 713;
UPDATE foods SET name_id = 'Tomat Kuning' WHERE id = 788;
UPDATE foods SET name_id = 'Labu siam' WHERE id = 790;

COMMIT;